---
title: "proj 4 clean data"
author: "Yuxin Zhu"
date: "2017/4/2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 0: Load the packages, specify directories
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(text2vec, dplyr, qlcMatrix, kernlab, knitr)
setwd("~/Documents/Columbia /2017 spring/ADS/proj 4")
```

## Step 1: Load data (not used)
```{r}
setwd("~/Documents/Columbia /2017 spring/ADS/proj 4/nameset")
filenames <- list.files(pattern = ".*txt")
names <- substr(filenames,1,nchar(filenames)-4)

# method 1 
for (i in names){
  filepath <- file.path("~/Documents/Columbia /2017 spring/ADS/proj 4/nameset",paste(i,".txt",sep=""))
  assign(i,data.frame(scan(filepath,
                      what = list(Coauthor = "", Paper = "", Journal = ""),
                      sep=">", quiet=TRUE,quote = ""),stringsAsFactors=FALSE))
}

# method 2 (better)
for (i in names){
  filepath <- file.path("~/Documents/Columbia /2017 spring/ADS/proj 4/nameset",paste(i,".txt",sep=""))
  temp <- stringr::str_replace_all(readLines(filepath),"[^a-zA-Z0-9_;<>\\s]", " ")
  temp2 <- strsplit(temp,"<>")
  temp3 <- plyr::ldply(temp2,rbind)
  colnames(temp3) <- c("Coauthor","Paper","Journal")
  assign(i,temp3)
}

```

## Process data 
```{r}
library(dplyr)
cleandata1 <- function(df){
  df$AuthorId <- sub("_.*","",df$Coauthor)
  df$PaperNo <- sub(".*_(\\w*)\\s.*", "\\1", df$Coauthor)
  df$Paper <- gsub("[[:punct:]]","",df$Paper)
  df$Journal <-  gsub("[[:punct:]]","",df$Journal)
  df$Coauthor <- gsub("<","",sub("^.*?\\s","", df$Coauthor))
  df <- mutate_each(df,funs(tolower))
  return(df)
}

cleandata2 <- function(df){
  uplength <- gregexpr(";",df$Coauthor[1],fixed=TRUE)[[1]][1]
  pattern1 <- substr(df$Coauthor[1],start=1,stop=uplength-1)
  a <- strsplit(pattern1," ")
  aa <-substr(a[[1]][1],1,1)
  b <-length(a[[1]])
 ## 修改
  pattern <- paste(aa,"[a-z]*[[:space:]]*[a-z]*[[:space:]]*[a-z]*[[:space:]]*[a-z]*[[:space:]]*[a-z]*[[:space:]]*",a[[1]][b],";*",sep='')
 ##
  df$Author <- regmatches(df$Coauthor,regexpr(pattern,df$Coauthor))
  df$Author <- gsub("[[:punct:]]","",df$Author)
  df$Coauthor <- gsub(pattern,"",df$Coauthor)
  df$Coauthor <- gsub("&|-","",df$Coauthor)
  temp <- plyr::ldply(strsplit(df$Coauthor,";"),rbind)
  df <- cbind(df,temp)
  df <- df[,-1]
  return(df)
}

#AKumarcl <- cleandata1(AKumar)
#AGuptacl <- cleandata1(AGupta)
#CChencl <- cleandata1(CChen)
#AGuptacl[145,1] <- "anoop gupta;wolf dietrich weber ;todd c mowry"
#AGuptacl[145,3] <- NA
# Aguptacl 145 no author name 
#AKumarcl <- cleandata2(AKumarcl)
#CChencl <- cleandata2(CChencl)
#AGuptacl <- cleandata2(AGuptacl)
#write.csv(AKumarcl,file="AKumarcl.csv")
#write.csv(AGuptacl,file="AGuptacl.csv")
#write.csv(CChencl,file="CChencl.csv")
```

### pattern(not use)
```{R}
# paste 
uplength <- gregexpr(";",df$Coauthor[1],fixed=TRUE)[[1]][1]
pattern1 <- substr(df$Coauthor[1],start=1,stop=uplength-1)
a <- strsplit(pattern1," ")
pattern <- paste(a[[1]][1],"([a-z][[:space:]]){0,10}",a[[1]][2],";*",sep='')
# real 
pattern_real <- "c([a-z][[:space:]]){0,10}chen;*"
```


### write a for loop
```{r}
library(plyr)
setwd("~/Documents/Columbia /2017 spring/ADS/proj 4/nameset")
filenames <- list.files(pattern = ".*txt")
names <- substr(filenames,1,nchar(filenames)-4)
a.list <- NULL

for (i in names){
  filepath <- file.path("~/Documents/Columbia /2017 spring/ADS/proj 4/nameset",paste(i,".txt",sep=""))
  temp <- stringr::str_replace_all(readLines(filepath),"[^a-zA-Z0-9_;<>\\s]", " ")
  temp2 <- strsplit(temp,"<>")
  temp3 <- plyr::ldply(temp2,rbind)
  colnames(temp3) <- c("Coauthor","Paper","Journal")
  a.list[[i]] <- temp3
}

# manually modifed data
b.list <- llply(a.list,cleandata1)
b.list[[1]][145,1] <- "anoop gupta;wolf dietrich weber ;todd c mowry"
b.list[[1]][145,3] <- NA
b.list[[5]][1342,1] <- "marinos  l   papazoglou  m     j lee"
b.list[[5]][1342,2] <- " using a unifying mediator in an environment of distributed heterogeneous databases"
b.list[[5]][1344,1] <-"c dellarocas  j lee  t w malone  k crowston  and b pentland"
b.list[[5]][1344,2] <-" using a process handbook to design organizational processes "
c.list <- llply(b.list,cleandata2)
list2env(c.list,envir = .GlobalEnv)
```

### Single-link Agglomerative clustering
```{R}
library(cluster)
agn <- agnes(x=predictorX[1:25,], diss = FALSE, stand = TRUE,
      method = "single")
DendAgn <-as.dendrogram(agn)
plot(DendAgn)
```
